CREATE TABLE GH_CATEGORY (
  id_category SERIAL PRIMARY KEY,
  no_name varchar(255) NOT NULL UNIQUE,
  dt_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dt_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

