CREATE TABLE GH_STORE_GAME (
  id_store_game SERIAL PRIMARY KEY,
  id_store INTEGER REFERENCES GH_STORE(id_store) ON DELETE CASCADE,
  id_game INTEGER REFERENCES GH_GAME(id_game) ON DELETE CASCADE,
  price DECIMAL(10, 2) NOT NULL,
  dt_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dt_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

