CREATE TABLE GH_WISHLIST_GAME (
    id_wishlist_game SERIAL PRIMARY KEY,
    id_user INTEGER NOT NULL,
    id_game INTEGER NOT NULL,
    dt_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    dt_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user FOREIGN KEY (id_user) REFERENCES GH_USER(id_user),
    CONSTRAINT fk_game FOREIGN KEY (id_game) REFERENCES GH_GAME(id_game)
);


