CREATE TYPE user_type AS ENUM ('COMMON', 'ADMIN', 'MODERATOR');

CREATE TYPE gender AS ENUM ('MALE', 'FEMALE', 'OTHER');

CREATE TYPE coupon_type AS ENUM ('VALUE', 'PERCENTAGE');

CREATE TYPE game_status AS ENUM ('NOT_PLAYED', 'PLAYING', 'FINISHED', 'ON_PAUSE');
