CREATE TABLE GH_GAME (
  id_game SERIAL PRIMARY KEY,
  id_developer INTEGER REFERENCES GH_DEVELOPER(id_developer) ON DELETE CASCADE,
  no_name VARCHAR(255) NOT NULL,
  dt_release TIMESTAMP,
  nu_rating DOUBLE PRECISION DEFAULT 0 NOT NULL,
  nu_total_evaluation INTEGER DEFAULT 0 NOT NULL,
  dt_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dt_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
