CREATE TABLE GH_PLATFORM (
  id_platform SERIAL PRIMARY KEY,
  no_name VARCHAR(255) NOT NULL,
  dt_created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  dt_updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);